### PR TITLE
Fix #1846 deployment order tests

### LINKED ISSUE #1846: TestDeploymentOrderServiceEndpointClient failed on Azure
## Failure Logs
https://circleci.com/gh/networkservicemesh/networkservicemesh/114198?pipelines-ui-opt-out

### PR DESCRIPTION
**Pull request by haiodo**
Fix #1846 deployment order tests

Signed-off-by: Andrey Sobolev <haiodo@xored.com>

## How Has This Been Tested?

- [x] Covered by existing integration testing
- [ ] Added integration testing to cover
- [ ] Tested locally
- [ ] Have not tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: test/integration/usecase_deployment_order_test.go [hunk 1]
```diff
@@ -182,10 +182,11 @@ func testDeploymentOrder(t *testing.T, order []Deployment) {
 	for _, deploy := range order {
 		waitgroup.Add(1)
 
+		dp := deploy
```
Comment (denis-tingajkin) [inline test/integration/usecase_deployment_order_test.go]: nice catch
