### PR TITLE
Reuse available workspace for new client

### LINKED ISSUE #2189: nsmd too many open files error
## Expected Behavior

I'm trying to do a stability testing with 10 NSCs by deploying and undeploying it multiple times. 
The deployment and cleanup should work seamlessly in all the runs.

## Current Behavior

In the 2nd or 3rd attempts of NSCs deployment, nsmdp fails to connect with nsmd, one NSC pod fails with admission error and other NSC pods goes into pending state.

## Failure Information (for bugs)

Here is the logs from nsmdp and nsmd on the failed worker node.

nsmdp log:
```
time="2020-09-14T14:11:57Z" level=info msg=">><<-- GRPC->/v1beta1.DevicePlugin/Allocate()=\"\" span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<-- request={\"container_requests\":[{\"devicesIDs\":[\"nsm-5\"]}]} span={}"
time="2020-09-14T14:11:57Z" level=info msg="==--> Allocate() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Client request for nsmdp resource... container_requests: <\n  devicesIDs: \"nsm-5\"\n>\n" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Requesting Workspace, device ID: nsm-5" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg="==----> RequestWorkspace() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Connecting to nsmd on socket: /var/lib/networkservicemesh/nsm.io.sock..."
time="2020-09-14T14:11:57Z" level=info msg="Requesting nsmd for client connection..."
time="2020-09-14T14:11:57Z" level=info msg=">><<---- /nsmdapi.NSMD/RequestClientConnection()=\"\" span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<---- request={\"workspace\":\"nsm-5\"} span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<---- response={} span={}"
time="2020-09-14T14:11:57Z" level=error msg=">><<---- error=rpc error: code = Unavailable desc = transport is closing span={}"
time="2020-09-14T14:11:57Z" level=info msg="Received Workspace <nil>" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=error msg="error talking to nsmd: rpc error: code = Unavailable desc = transport is closing" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg="AllocateResponse: &AllocateResponse{ContainerResponses:[]*ContainerAllocateResponse{},}" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg=">><<-- response={} span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<-- GRPC->/v1beta1.DevicePlugin/Allocate()=\"\" span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<-- request={\"container_requests\":[{\"devicesIDs\":[\"nsm-4\"]}]} span={}"
time="2020-09-14T14:11:57Z" level=info msg="==--> Allocate() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Client request for nsmdp resource... container_requests: <\n  devicesIDs: \"nsm-4\"\n>\n" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Requesting Workspace, device ID: nsm-4" operation=Allocate span="{}"
time="2020-09-14T14:11:57Z" level=info msg="==----> RequestWorkspace() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Connecting to nsmd on socket: /var/lib/networkservicemesh/nsm.io.sock..."
time="2020-09-14T14:12:11Z" level=info msg="==--> ListAndWatch-20() span:{}"
time="2020-09-14T14:12:11Z" level=info msg="==----> recieveWorkspaces() span:{}"
time="2020-09-14T14:12:11Z" level=info msg="Request workspaces list" operation=recieveWorkspaces span="{}"
time="2020-09-14T14:12:11Z" level=info msg="==------> enumWorkspaces() span:{}"
```

nsmd log:
```
time="2020-09-14T14:11:57Z" level=info msg=">><<-- GRPC->/nsmdapi.NSMD/RequestClientConnection()=\"\" span={}"
time="2020-09-14T14:11:57Z" level=info msg=">><<-- request={\"workspace\":\"nsm-5\"} span={}"
time="2020-09-14T14:11:57Z" level=info msg="==--> RequestClientConnection() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Requested client connection to nsmd : workspace:\"nsm-5\" " operation=RequestClientConnection span="{}"
time="2020-09-14T14:11:57Z" level=info msg="==----> Workspace:nsm-5() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new workspace: nsm-5" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg=">><<---- restore=false span={}"
time="2020-09-14T14:11:57Z" level=info msg="==------> clearContents() span:{}"
time="2020-09-14T14:11:57Z" level=info msg="Removing exist content im /var/lib/networkservicemesh/nsm-5" operation=clearContents span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new directory: /var/lib/networkservicemesh/nsm-5" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new listener on: /var/lib/networkservicemesh/nsm-5/nsm.server.io.sock" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new NetworkServiceRegistryServer" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new MonitorConnectionServer" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg="Creating new NetworkServiceServer" operation="Workspace:nsm-5" span="{}"
time="2020-09-14T14:11:57Z" level=info msg="LocalConnection - Serve starting..."
2020/09/14 14:11:57 too many open files
```

As per the above log, nsmd is crashed with `too many open files` error and never get restarted after this error. 

The specified error in this [link ](https://github.com/networkservicemesh/networkservicemesh/blob/master/controlplane/pkg/remote/connection_service.go#L130)were also seen in the nsmd logs during NSC deletions, not sure if it leads to corresponding client connection's workspace grpc server and its file descriptors not getting cleaned up. 

The number of socket files under `/var/lib/networkservicemesh/nsm*`  directory and `lsof -p <nsmd-pid>| grep -c "protocol: UNIX"` command output are always same even after deleting the clients.

## Steps to Reproduce

1. Increase the replicas to 10 in [nsc.tpl](https://github.com/networkservicemesh/networkservicemesh/blob/master/deployments/helm/client/templates/nsc.tpl#L8).
2. `make helm-install-endpoint helm-install-client`
3. `make helm-delete-endpoint helm-delete-client`
4. Repeat steps 2 and 3 few times.

## Context

* Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:39:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by pperiyasamy**
This fix attempts to fix nsmd's client grpc fd leakage by reusing
the existing workspace when nsmdp requests for workspace with
socket id which was already available. It would fix #2189 issue.

Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

## How Has This Been Tested?

- [ ] Covered by existing integration testing
- [ ] Added integration testing to cover
- [x] Tested locally
- [ ] Have not tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: controlplane/pkg/nsmd/nsmd.go [hunk 1]
```diff
@@ -127,6 +127,22 @@ func (nsm *nsmServer) RequestClientConnection(ctx context.Context, request *nsmd
 
 	span.Logger().Infof("Requested client connection to nsmd : %+v", request)
 
+	nsm.Lock()
+	workspace, ok := nsm.workspaces[request.Workspace]
```
Comment (haiodo) [inline controlplane/pkg/nsmd/nsmd.go:131]: I think it could be done using Close call on existing workspace to close all used resources and create new ones, it as well will cleanup folder from any existing artifacts.
```suggestion
	// Check if workspace are exists, we should clean resources and reuse-it
	if workspace, ok := nsm.workspaces[request.Workspace]; ok {
		workspace.Close()
	}
```

File: controlplane/pkg/nsmd/nsmd.go [hunk 2]
```diff
@@ -127,6 +127,22 @@ func (nsm *nsmServer) RequestClientConnection(ctx context.Context, request *nsmd
...
+	nsm.Unlock()
+	if ok {
```
Comment (haiodo) [inline controlplane/pkg/nsmd/nsmd.go:133]: In this case this logic will not be required.

**Comment by edwarnicke** [comment]
@pperiyasamy I *really* hope the solution is this easy :)  And I suspect it is... looping in @haiodo who I suspect was most recently close to this code :)

**Comment by edwarnicke** [comment]
@pperiyasamy Looks like Azure was being grumpy on your CI run, lets see what it looks like when you submit revisions :)

File: controlplane/pkg/nsmd/nsmd.go (hunk 1 above)
Comment (pperiyasamy) [reply controlplane/pkg/nsmd/nsmd.go:131]: @haiodo @edwarnicke  Do you see any issue with reusing the existing workspace ?  Even in case of normal scenario while creating NSC it looks RequestWorkspace is called 4 times (3 with same socket id and 4th one with different socket id), I think this is because when nsmdp's  Allocate is called from device manager, AllocateRequest contains 4 ContainerRequests for each NSC. so this change would lead to recreating the same workspace again and again. Please let me know.

Comment (haiodo) [reply controlplane/pkg/nsmd/nsmd.go:131]: This is unexpected actually, will check.

**Comment by edwarnicke** [comment]
@2191 may have the fix for the Azure issues we are seeing here... lets wait for its CI to complete and see :)

**Comment by edwarnicke** [comment]
Apparently #2191 isn't fixing the issue... looping in more expertise: https://cloud-native.slack.com/archives/CHQNNUPN1/p1600877542032500

**Comment by haiodo** [comment]
@peri could you please rebase on master to check Azure, so we could merge it. Thanks.

**Comment by edwarnicke** [comment]
@pperiyasamy If you rebase again... I think we've fixed the Azure issues :)

**Comment by edwarnicke** [comment]
@haido @denis-tingajkin Any insight as to why CI may still be failing?

**Comment by haiodo** [comment]
Test with memif benchmarking is filing sometime, not related to this changes. I've merged PR 👍

**Comment by denis-tingajkin** [comment]
Yes, it is vpp issue https://github.com/networkservicemesh/networkservicemesh/issues/2028
